[build-system]
requires = ["setuptools>=61.0.0", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "iri2026"
version = "2026.0.0"
description = "IRI-2026 International Reference Ionosphere from Python"
authors = [{name = "Xiangning Chu", email = "xiangning.chu@lasp.colorado.edu"}]
maintainers = [{name = "Xiangning Chu", email = "xiangning.chu@lasp.colorado.edu"}]
keywords = ["thermosphere", "ionosphere"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Intended Audience :: Science/Research",
  "Programming Language :: Fortran",
  "Topic :: Scientific/Engineering :: Atmospheric Science"
]
dynamic = ["readme"]
requires-python = ">=3.9"
dependencies = ["numpy", "xarray", "python-dateutil"]

[project.urls]
Homepage = "https://github.com/xnchu/iri2026"
Upstream = "https://irimodel.org/IRI-2026/"

[project.optional-dependencies]
tests = ["pytest"]
lint = ["flake8", "flake8-bugbear", "flake8-builtins", "flake8-blind-except", "mypy", "types-python-dateutil"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.black]
line-length = 99

[tool.mypy]
files = ["src"]
ignore_missing_imports = true
